language: node_js
node_js: "12"
cache:
  yarn: true

install:
  - yarn

script:
  - yarn ci:lint
  - yarn ci:test
  - yarn ci:build

before_deploy:
  - git checkout ${TRAVIS_BRANCH}

deploy:
  provider: script
  script: yarn ci:release && yarn ci:deploy
  skip_cleanup: true
  on:
    branch: master
